# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18DS18TJr_InuFI9jpKGlVUWsKvT-1oQV
"""

from google.colab import drive 
drive.mount('/content/drive')

# 19034598_3mm_Retina_OS_20180131.png

import cv2
import numpy as np
import matplotlib.pyplot as plt

# crop_img = img[y:y+h, x:x+w]
# cv2.imshow("cropped", crop_img)

img_path = '/content/patch_thre.png'

img = cv2.imread(img_path, cv2.IMREAD_COLOR)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

y = 175
h = 50
x = 150
w = 50

crop_img = img[y:y+h, x:x+w]
crop_img = cv2.resize(crop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
plt.imshow(crop_img)

from PIL import Image
re = Image.fromarray(crop_img.astype(np.uint8))
mm = "ss_" + img_path.split("/")[-1]
path_save_name = mm
re.save(path_save_name)

# 19034598_3mm_Retina_OS_20180131.png

import cv2
import numpy as np
import matplotlib.pyplot as plt

img_path = '/content/drive/My Drive/new_imgs/19034598_3mm_Retina_OS_20180131.png'

img = cv2.imread(img_path, cv2.IMREAD_COLOR)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

y = 175
h = 50
x = 150
w = 50

crop_img = img[y:y+h, x:x+w]
crop_img = cv2.resize(crop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
lx, ly, rx, ry = 110 ,75, 151, 115
cv2.rectangle(crop_img, (round(lx), round(ly)), (round(rx), round(ry)), (0, 0, 255), 4)
lx, ly, rx, ry = 120 ,78, 161, 120
cv2.rectangle(crop_img, (round(lx), round(ly)), (round(rx), round(ry)), (0, 0, 255), 4)

lx, ly, rx, ry = 210 ,110, 233, 137
cv2.rectangle(crop_img, (round(lx), round(ly)), (round(rx), round(ry)), (0, 0, 255), 4)
lx, ly, rx, ry = 250 ,-3, 300, 25
cv2.rectangle(crop_img, (round(lx), round(ly)), (round(rx), round(ry)), (0, 0, 255), 4)
# crop_img = img[y:y+h, x:x+w]
plt.imshow(crop_img)

from PIL import Image
re = Image.fromarray(crop_img.astype(np.uint8))
mm = "ss_" + img_path.split("/")[-1]
path_save_name = mm
re.save(path_save_name)

re_path = '/content/patch_faster.png'

mg = cv2.imread(re_path, cv2.IMREAD_COLOR)
mg = cv2.cvtColor(mg, cv2.COLOR_BGR2RGB)

ccrop_img = mg[y:y+h, x:x+w]
ccrop_img = cv2.resize(ccrop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
plt.imshow(ccrop_img)

re = Image.fromarray(ccrop_img.astype(np.uint8))
mm = "ss_" + re_path.split("/")[-1]
path_save_name = mm
re.save(path_save_name)

re_path = '/content/patch_retina.png'

mg = cv2.imread(re_path, cv2.IMREAD_COLOR)
mg = cv2.cvtColor(mg, cv2.COLOR_BGR2RGB)

ccrop_img = mg[y:y+h, x:x+w]
ccrop_img = cv2.resize(ccrop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
plt.imshow(ccrop_img)

re = Image.fromarray(ccrop_img.astype(np.uint8))
mm = "ss_" + re_path.split("/")[-1]
path_save_name = mm
re.save(path_save_name)

re_path = '/content/no_thre.png'

mg = cv2.imread(re_path, cv2.IMREAD_COLOR)
mg = cv2.cvtColor(mg, cv2.COLOR_BGR2RGB)

ccrop_img = mg[y:y+h, x:x+w]
ccrop_img = cv2.resize(ccrop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
plt.imshow(ccrop_img)

re = Image.fromarray(ccrop_img.astype(np.uint8))
mm = "ss_" + re_path.split("/")[-1]
path_save_name = mm
re.save(path_save_name)

re_path = '/content/no_patch_retina.png'

mg = cv2.imread(re_path, cv2.IMREAD_COLOR)
mg = cv2.cvtColor(mg, cv2.COLOR_BGR2RGB)

ccrop_img = mg[y:y+h, x:x+w]
ccrop_img = cv2.resize(ccrop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
plt.imshow(ccrop_img)

re_path = '/content/no_patch_faster.png'

mg = cv2.imread(re_path, cv2.IMREAD_COLOR)
mg = cv2.cvtColor(mg, cv2.COLOR_BGR2RGB)

ccrop_img = mg[y:y+h, x:x+w]
ccrop_img = cv2.resize(ccrop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
plt.imshow(ccrop_img)

re = Image.fromarray(ccrop_img.astype(np.uint8))
mm = "ss_" + re_path.split("/")[-1]
path_save_name = mm
re.save(path_save_name)

re_path = '/content/filter.png'

mg = cv2.imread(re_path, cv2.IMREAD_COLOR)
mg = cv2.cvtColor(mg, cv2.COLOR_BGR2RGB)

ccrop_img = mg[y:y+h, x:x+w]
ccrop_img = cv2.resize(ccrop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
plt.imshow(ccrop_img)

re = Image.fromarray(ccrop_img.astype(np.uint8))
mm = "ss_" + re_path.split("/")[-1]
path_save_name = mm
re.save(path_save_name)

re_path = '/content/eoeoeo.png'

mg = cv2.imread(re_path, cv2.IMREAD_COLOR)
mg = cv2.cvtColor(mg, cv2.COLOR_BGR2RGB)

y = 175 + 32
h = 50
x = 150 + 25
w = 60

ccrop_img = mg[y:y+h, x:x+w]
ccrop_img = cv2.resize(ccrop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
plt.imshow(ccrop_img)

re = Image.fromarray(ccrop_img.astype(np.uint8))
mm = "ss_" + re_path.split("/")[-1]
path_save_name = mm
re.save(path_save_name)

import cv2
import numpy as np
import matplotlib.pyplot as plt

# crop_img = img[y:y+h, x:x+w]
# cv2.imshow("cropped", crop_img)

img_path = '/content/patch_thre.png'

img = cv2.imread(img_path, cv2.IMREAD_COLOR)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

y = 175
h = 50
x = 150
w = 50

crop_img = img[y:y+h, x:x+w]
crop_img = cv2.resize(crop_img, dsize=(300, 300), interpolation=cv2.INTER_AREA)
plt.imshow(crop_img)

from PIL import Image
re = Image.fromarray(crop_img.astype(np.uint8))
mm = "ss_" + img_path.split("/")[-1]
path_save_name = mm
re.save(path_save_name)